Board listeners
softenguvu/chess-se pull request #29
Opened 2023-03-22 23:36 UTC by slayerhintze

Added board classes event listeners

2023-03-23 03:04 UTC, jbeBan commented on index.html
Thank you for catching that extra head tag.

2023-03-23 03:08 UTC, jbeBan requested changes

2023-03-23 03:08 UTC, jbeBan commented on js/index.js
> +    })
Each call to `addEventListener()` is missing a semicolon at the end of the statement. Please add a semicolon at the end of each call to `addEventListener()`.

2023-03-28 04:41 UTC, jbeBan approved these changes
Perfect! Thanks for making those changes.

2023-03-29 22:55 UTC, Jason-mcm approved these changes
Looks great!

2023-04-01 01:30 UTC, merged