Add board undo
softenguvu/chess-se pull request #49
Opened 2023-04-06 00:03 UTC by slayerhintze

Added undo logic to the event listener for the undo button and the board class

2023-04-08 02:00 UTC, jbeBan requested changes

2023-04-08 02:00 UTC, jbeBan commented on js/index.js
> +    BOARD.lastPieceMoved.undo(BOARD)
You'll need to check if a piece has been moved before calling `undo()` so that `undo()` is not called on `null`.

2023-04-13 21:22 UTC, slayerhintze commented
Made changes suggested in pull request, just need re-review

2023-04-13 22:36 UTC, jbeBan approved these changes
Everything looks good now. Thank you!

2023-04-14 16:49 UTC, merged