King Unit Tests
softenguvu/chess-se pull request #59
Opened 2023-04-19 04:31 UTC by Jason-mcm

King class unit tests

2023-04-19 17:03 UTC, natalinamateaki requested changes
Looks great! I think one more thing that would be good to test for is to ensure that possibleMoves() doesn't add a square in it's path that has a piece with the same player Id.

2023-04-19 17:15 UTC, natalinamateaki requested changes
On line 148 in rook-test.js, I think you meant to write "board.board[0][1] = rook3".

2023-04-19 17:15 UTC, natalinamateaki commented on test/rook-test.js
Looks great, only thing I found is that on line 148, I think you meant to write "board.board[0][1] = rook3".

2023-04-20 20:57 UTC, natalinamateaki approved these changes
Looks great! Good work!

2023-04-22 00:39 UTC, jbeBan approved these changes
💯

2023-04-22 02:45 UTC, merged